name: Run Monthly Momentum Script

on:
  schedule:
    # Run on the 1st of every month at 21:10 UTC (~5:10 PM New York, after month-end settles)
    - cron: '10 21 1 * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: momentum-monthly
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    env:
      TZ: America/New_York
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUNBUFFERED: '1'
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Run momentum script (attempt 1)
        id: run1
        run: |
          python momentum_script.py > run.log 2>&1 || echo "FAILED" > .failed

      - name: Retry once on failure (attempt 2)
        if: hashFiles('.failed') != ''
        run: |
          echo "First attempt failed; retrying in 20s..."
          sleep 20
          python momentum_script.py >> run.log 2>&1 || exit 1

      - name: Upload logs/artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: momentum-run-${{ github.run_id }}
          path: |
            run.log
            # If your script writes the HTML email body to /tmp/email.html, include it:
            /tmp/email.html
